[phases.setup]
nixPkgs = ["nodejs_20", "npm"]

[phases.install]
cmds = ["npm ci"]

[phases.build]
cmds = [
  "npx vite build",
  "npx esbuild server/index.ts --platform=node --packages=external --bundle --format=esm --outdir=dist --minify"
]

[start]
cmd = "npm start"

[variables]
NODE_ENV = "production"